### ISSUE TITLE
unable to complete initial setup; face unlock not woking

### ISSUE THREAD

**Issue by oneofmanyacdcfanstoo** [ChonDoit/treble_alphadroid_patches#5]
On first boot, I am unable to complete the initial setup because face unlock will not work despite multiple attempts. It works fine on my stock ROM. The only way to proceed for me is to reinstall the gsi and skip creating a pin during first time setup, which in turn bypasses face unlock setup. Suggest to remove face unlock from first boot setup or make it skippable.

**Comment by ChonDoit** [comment]
It's already avoidable, just don't setup any fucking security at all

**Comment by oneofmanyacdcfanstoo** [comment]
And who the fuck would know to do that the first time they install this ROM? Why should that be a prerequisite? And why cuss at someone for reporting a bug?


-------- Original Message --------

**Comment by ChonDoit** [comment]
> And who the fuck would know to do that the first time they install this ROM? Why should that be a prerequisite? And why cuss at someone for reporting a bug?
> […](#)
> -------- Original Message -------- From: ChonDoit ***@***.***> Sent: September 7, 2023 10:27:17 PM EDT To: ChonDoit/treble_alphadroid_patches ***@***.***> Cc: oneofmanyacdcfanstoo ***@***.***>, Author ***@***.***> Subject: Re: [ChonDoit/treble_alphadroid_patches] unable to complete initial setup; face unlock not woking (Issue #5) It's already avoidable, just don't setup any fucking security at all
> -- Reply to this email directly or view it on GitHub: [#5 (comment)](https://github.com/ChonDoit/treble_alphadroid_patches/issues/5#issuecomment-1710988653) You are receiving this because you authored the thread. Message ID: ***@***.***>

A proper bug report include logs and useful info :3

And yeah, first time testing something you will not try to setup everything on setup wizard.
Good luck sweetie
